name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --add-data "std.pkl;." --add-data "XG5.dat;." Tool.py

    - name: Upload artifact to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/Tool.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
